### ISSUE TITLE
Epic: Basic HPACK Implementation

### ISSUE THREAD

**Issue by DrkWithT** [DrkWithT/H2Plus-HTTP2-Server#7]
As a web server programmer, I want to implement a working portion of the HPACK compression scheme for HTTP/2 so that later header encoding and decoding is acceptable by clients such as _cURL_.

**Children Items:**
- [x] TechFeature: Huffman Coding Utilities
- [x] TechFeature: Header Indexing Table
- [ ] TechFeature: Integer & String Utilities

**Comment by DrkWithT** [comment]
This item is done because its final child feature has been completed: integer utilities are finished.
